-- SQLite-compatible reminders dataset seed
CREATE TABLE IF NOT EXISTS reminders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    tag TEXT NOT NULL,
    priority TEXT NOT NULL,
    time_slot TEXT NOT NULL,
    risk_level TEXT NOT NULL,
    en TEXT NOT NULL,
    te TEXT NOT NULL,
    hi TEXT NOT NULL,
    UNIQUE(tag, risk_level, en)
);

INSERT OR IGNORE INTO reminders (tag, priority, time_slot, risk_level, en, te, hi) VALUES
('calcium_low','high','morning','all','Start your day with a calcium-rich breakfast','కాల్షియం అల్పాహారంతో రోజును ప్రారంభించండి','कैल्शियम नाश्ते से दिन शुरू करें'),
('sunlight_low','high','morning','all','Get 20 minutes of sunlight daily','20 నిమిషాలు సూర్యకాంతిలో ఉండండి','20 मिनट धूप लें'),
('exercise_low','high','evening','all','Do at least 30 minutes of exercise','30 నిమిషాలు వ్యాయామం చేయండి','30 मिनट व्यायाम करें'),
('protein_low','high','evening','all','Include protein-rich meals in your diet','ప్రోటీన్ ఆహారం తీసుకోండి','प्रोटीन युक्त भोजन लें'),
('hydration_low','medium','afternoon','all','Drink enough water throughout the day','రోజంతా నీరు తాగండి','दिन भर पानी पिएँ'),
('diet_poor','medium','afternoon','all','Include leafy vegetables in your meals','ఆకుకూరలు భోజనంలో చేర్చండి','हरी सब्जियाँ खाएँ'),
('fruit_intake_low','medium','afternoon','all','Eat seasonal fruits daily','ప్రతి రోజు పండ్లు తినండి','रोज फल खाएँ'),
('vitamin_c_low','medium','weekly','all','Consume Vitamin C rich fruits weekly','విటమిన్ C పండ్లు తినండి','विटामिन C फल खाएँ'),
('junk_food','high','night','all','Avoid junk food and soft drinks','జంక్ ఫుడ్ నివారించండి','जंक फूड से बचें'),
('caffeine','medium','any','all','Limit caffeine intake','కాఫీన్ తగ్గించండి','कैफीन कम करें'),
('smoking','high','any','all','Stop smoking immediately','ధూమపానం మానండి','धूम्रपान छोड़ें'),
('alcohol','high','any','all','Avoid alcohol consumption','మద్యం నివారించండి','शराब से बचें'),
('posture_bad','medium','morning','all','Maintain correct posture while working','సరైన భంగిమ పాటించండి','सही मुद्रा रखें'),
('sitting_long','medium','any','all','Avoid sitting for long hours continuously','ఎక్కువసేపు కూర్చోవద్దు','लंबे समय तक बैठने से बचें'),
('mobility_low','medium','evening','all','Practice flexibility exercises regularly','వశ్యత వ్యాయామాలు చేయండి','लचीलापन व्यायाम करें'),
('balance_low','medium','evening','all','Perform balance training exercises','బ్యాలెన్స్ వ్యాయామాలు చేయండి','संतुलन व्यायाम करें'),
('symptom_tracking','medium','any','all','Track your symptoms regularly in the app','లక్షణాలు నమోదు చేయండి','लक्षण दर्ज करें'),
('weight_monitoring','medium','weekly','all','Monitor your body weight weekly','బరువు గమనించండి','वजन देखें'),
('pain_monitoring','high','any','all','Monitor joint or bone pain daily','నొప్పి గమనించండి','दर्द पर ध्यान दें'),
('doctor_visit','high','any','moderate','Visit a doctor every 2 months','ప్రతి 2 నెలలకు డాక్టర్‌ను కలవండి','हर 2 महीने डॉक्टर से मिलें'),
('doctor_visit','high','any','high','Consult a doctor immediately','వెంటనే డాక్టర్‌ను సంప్రదించండి','तुरंत डॉक्टर से मिलें'),
('medication','high','any','high','Do not skip prescribed medication','మందులు మానేయకండి','दवा न छोड़ें'),
('supplements','high','morning','high','Take calcium and Vitamin D supplements','కాల్షియం, విటమిన్ D తీసుకోండి','कैल्शियम और विटामिन D लें'),
('physiotherapy','medium','evening','high','Perform physiotherapy exercises regularly','ఫిజియోథెరపీ చేయండి','फिजियोथेरेपी करें'),
('fall_risk','high','any','moderate','Avoid slippery surfaces and falls','జారిపోకుండా జాగ్రత్తగా ఉండండి','फिसलन से बचें'),
('footwear','medium','any','all','Wear proper footwear for support','సరైన పాదరక్షలు ధరించండి','सही जूते पहनें'),
('grab_bars','high','any','high','Install grab bars at home','గ్రాబ్ బార్లు అమర్చండి','ग्रैब बार लगाएँ'),
('lighting','medium','night','all','Ensure proper lighting at home','ఇంట్లో సరైన వెలుతురు ఉంచండి','घर में रोशनी रखें'),
('heavy_lifting','high','any','high','Avoid heavy lifting activities','భారీ వస్తువులు ఎత్తవద్దు','भारी वजन न उठाएँ'),
('sudden_movement','high','any','high','Avoid sudden movements','అకస్మాత్తుగా కదలికలు చేయవద్దు','अचानक गतिविधि से बचें'),
('supervised_exercise','high','evening','high','Perform exercises under supervision','పర్యవేక్షణలో వ్యాయామం చేయండి','निगरानी में व्यायाम करें'),
('sleep_poor','medium','night','all','Ensure 7-8 hours of sleep','7-8 గంటలు నిద్ర పొందండి','7-8 घंटे सोएँ'),
('sleep_schedule','medium','night','all','Maintain a consistent sleep schedule','నిద్ర సమయం పాటించండి','नींद का समय रखें'),
('vitamin_d_low','high','morning','all','Ensure adequate Vitamin D intake through diet or sunlight','విటమిన్ D తీసుకోండి','विटामिन D लें'),
('calcium_sources','medium','afternoon','all','Include milk, curd, or paneer in your meals','పాలు, పెరుగు తీసుకోండి','दूध या दही लें'),
('protein_sources','medium','evening','all','Include eggs, pulses, or nuts for protein','గుడ్లు లేదా పప్పులు తీసుకోండి','अंडा या दाल खाएँ'),
('salt_high','medium','any','all','Reduce salt intake to maintain bone health','ఉప్పు తగ్గించండి','नमक कम करें'),
('strength_training','high','evening','all','Do strength training exercises regularly','బలం వ్యాయామాలు చేయండి','शक्ति व्यायाम करें'),
('joint_stiffness','medium','morning','all','Perform joint mobility exercises daily','జాయింట్ వ్యాయామాలు చేయండి','जोड़ व्यायाम करें'),
('stretching','medium','morning','all','Do stretching exercises to improve flexibility','స్ట్రెచింగ్ చేయండి','स्ट्रेचिंग करें'),
('walking','high','evening','all','Walk at least 30 minutes daily','రోజూ నడవండి','रोज चलें'),
('slippery_floor','high','any','moderate','Avoid walking on wet or slippery floors','జారి పడే ప్రదేశాలు నివారించండి','फिसलन वाली जगह से बचें'),
('stairs_caution','medium','any','all','Use handrails while climbing stairs','మెట్లు ఎక్కేటప్పుడు జాగ్రత్తగా ఉండండి','सीढ़ियों पर सावधानी रखें'),
('assist_device','high','any','high','Use walking aids if necessary','వాకింగ్ సపోర్ట్ వాడండి','वॉकिंग सपोर्ट लें'),
('home_safety','medium','any','all','Keep home free from obstacles to prevent falls','ఇంటిని అడ్డంకుల్లేకుండా ఉంచండి','घर साफ रखें'),
('routine','medium','morning','all','Maintain a consistent daily routine','రోజువారీ అలవాట్లు పాటించండి','रोजाना दिनचर्या रखें'),
('activity','medium','any','all','Stay physically active throughout the day','రోజంతా చురుకుగా ఉండండి','सक्रिय रहें'),
('breaks','medium','any','all','Take short breaks during long work sessions','మధ్య మధ్యలో విరామం తీసుకోండి','बीच-बीच में ब्रेक लें'),
('pain_increase','high','any','high','Seek medical help if pain increases','నొప్పి పెరిగితే డాక్టర్‌ను సంప్రదించండి','दर्द बढ़े तो डॉक्टर से मिलें'),
('weakness','medium','weekly','all','Monitor body weakness regularly','బలహీనత గమనించండి','कमजोरी देखें'),
('fatigue','medium','any','all','Avoid overexertion and fatigue','అతిగా శ్రమించవద్దు','अधिक मेहनत न करें'),
('emergency_contact','high','any','high','Keep emergency contact easily accessible','అత్యవసర నంబర్ సిద్ధంగా ఉంచండి','आपातकालीन नंबर रखें'),
('followup','high','monthly','high','Attend regular follow-up checkups','తరచుగా డాక్టర్‌ను కలవండి','नियमित जांच कराएँ'),
('bone_density_test','medium','monthly','moderate','Consider bone density testing periodically','బోన్ టెస్ట్ చేయించండి','हड्डी जांच कराएँ'),
('early_sleep','medium','night','all','Sleep early for better recovery','తొందరగా నిద్రపోండి','जल्दी सोएँ'),
('screen_time','medium','night','all','Avoid screen time before sleep','నిద్రకు ముందు మొబైల్ ఉపయోగించవద్దు','सोने से पहले मोबाइल न देखें'),
('hydration_reminder','medium','morning','all','Start your day with a glass of water','రోజును నీటితో ప్రారంభించండి','दिन की शुरुआत पानी से करें'),
('sunlight_consistency','medium','morning','all','Maintain consistent daily sunlight exposure','ప్రతి రోజు సూర్యకాంతి పొందండి','रोज धूप लें'),
('social_activity','low','any','all','Stay socially active to maintain overall health','సామాజికంగా చురుకుగా ఉండండి','सामाजिक रूप से सक्रिय रहें'),
('caregiver_support','high','any','high','Ensure caregiver or family support for daily activities','సహాయం కోసం కుటుంబ సభ్యులను ఆశ్రయించండి','परिवार की सहायता लें');
